// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuIPjZIGMpVK8RiYKsMjAOmfGgcVZ0QEY',
    appId: '1:143602791092:web:7840c5411fb17204859de1',
    messagingSenderId: '143602791092',
    projectId: 'textly-8615a',
    authDomain: 'textly-8615a.firebaseapp.com',
    storageBucket: 'textly-8615a.appspot.com',
    measurementId: 'G-JMXYFZBRTD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiEchZfPMAumN2ece6z0kOpTtjowVhB8k',
    appId: '1:143602791092:android:f18608fce298496c859de1',
    messagingSenderId: '143602791092',
    projectId: 'textly-8615a',
    storageBucket: 'textly-8615a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqlQHgxWCiW8tBoSbZpEN35eAsbCwOBNo',
    appId: '1:143602791092:ios:c71ea3ad44fc25a6859de1',
    messagingSenderId: '143602791092',
    projectId: 'textly-8615a',
    storageBucket: 'textly-8615a.appspot.com',
    iosClientId: '143602791092-p5e2o37aegev5r0pe9chpusecqbl1mnm.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );
}
